amino_acid = 'MFDSPKETASLAGIDTSFQAAIDQGKINGAIFLASNAKSDFTYTNTIGERTLLSGEKQPLQADNVIYLASGTKIIAAIAALQCVEDGLIALDTDVSSIAPELANKQIITGWSEETDTPILEPATRPITFEMLLKHTSGMSYHFFNPLLLKWCKKYDQLEEGQTRPVEEAFAYPLTYQPGAGWMYSPGLDWAGRIVERLTGKTLGQFAQERIFDPLGISSAQFHPVTREDLRARMVDLNPNDPNGIGIAVVGSGESNKRSRGDFGGHGLFIGASDYAKVIHAVLVNDGKLFKPETGELMVQDRLTPEEAAGHQVALAGPIGPFFRVGTEKKAGYGLSGHVNLEDEDGWYGDHTLSWGGGMTLAWFADRKNDLAGVVAVQATIPTDVPAVTELKQVFRKDIYRKYAAWKEKRSS'
amino_acids = 'HMDTTFQAAIDTGKINGAVVCATDAQGHFVYNKATGERTLLSGEKQPQQLDDVLYLAAATKLITTIAALQCVEDGLLSLDGDLSSIAPELAAKYVLTGFTDDESPLDDPPARPITLKMLLTHSSGTSYHFLDPSIAKWRAQYANPENEKPRLVEEMFTYPLSFQPGTGWMYGPGLDWAGRVVERVTGGTLMEFMQKRIFDPLGITDSQFYPVTREDLRARLVDLNPSDPGALGSAVIGGGGEMNLRGRGAFGGHGLFLTGLDFVKILRSLLANDGMLLKPAAVDNMFQQHLGPEAAASHRAALASPLGPFFRVGTDPETKVGYGLGGLLTLEDVDGWYGERTLTWGGGLTLTWFIDRKNNLCGVGAIQAVLPVDGDLMADLKQTFRHDIYRKYSAWKGQQ'
amino_acid2 = 'MFDSPKETTSLAGIDTSFQAAIDQGKINGAIILASNAKGDFTYTNTIGERTLLSGEKQPLQTDNVVYLASGTKIIAAIAALQCVEDGLIALDTDVSSVAPELADKQIITGWSEESDTPILEPATRPITFEMLLKHTSGMSYHFFNPLLLKWCKKYDQLEEGQTRPVEEAFTYPLTYQPGAGWMYSPGLDWAGRIVERLTGKTLGQFAQERIFDPLSIDSAQFHPVTREDLRARMVDLNPNDPNGIGIAVVGSGESNKRSRGDFGGHGLFIGASDYAKVIHAVLVNDGKLFKPGTGELMVQDRLTPEEATGHQVALAGPIGPFFRVGTEKKAGYGLSGHVNLEDEDRWYGDHTLSWGGGMTLAWFADRKNDLAGVVAVQATIPTDVPAVTELKQVFRKDIYRKYGAWKEKQGS'
mass_table = {
'A':  71.03711, 'C':  103.00919, 'D':  115.02694, 'E':  129.04259,
'F': 147.06841, 'G':   57.02146, 'H':  137.05891, 'I':  113.08406,
'K': 128.09496, 'L':  113.08406, 'M':  131.04049, 'N':  114.04293,
'P':  97.05276, 'Q':  128.05858, 'R':  156.10111, 'S':   87.03203,
'T': 101.04768, 'V':   99.06841, 'W':  186.07931, 'Y':   163.06333
}
mass_total = 0
for x in amino_acid2:
    mass_total += mass_table[x]
print(mass_total)



# Hydrophobic = ['ALA','PHE','ILE','LEU','MET','PRO','VAL','TRP','GLY']
# Hydrophilic = ['CYS','ASN','GLN','SER','THR','TYR','ASP','GLU','HIS','LYS','ARG']
# aa_codes = {
#     'ALA':'A','CYS':'C','ASP':'D','GLU':'E',
#     'PHE':'F','GLY':'G','HIS':'H','LYS':'K',
#     'ILE':'I','LEU':'L','MET':'M','ASN':'N',
#     'PRO':'P','GLN':'Q','ARG':'R','SER':'S',
#     'THR':'T','VAL':'V','TYR':'Y','TRP':'W'}  
# for x in range(len(Hydrophilic)):Hydrophilic[x] = aa_codes[Hydrophilic[x]]
# for x in range(len(Hydrophobic)):Hydrophobic[x] = aa_codes[Hydrophobic[x]]
# count_Hydrophilic, count_Hydrophobic = 0, 0
# for x in range(len(amino_acid)):
#     if amino_acid[x] in Hydrophilic:
#         count_Hydrophilic += 1
#     elif amino_acid[x] in Hydrophobic:
#         count_Hydrophobic += 1
# print(count_Hydrophilic, count_Hydrophobic)